name: Build and Deploy op-geth

on:
  push:
    branches:
      - optimism

env:
  REGISTRY: "registry.digitalocean.com/sigil"
  DEPLOYMENT_NAME: op-geth
  CONTAINER_NAME: op-geth

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build container image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ env.REGISTRY }}/${{ env.CONTAINER_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 1200

      - name: Push image to DO Container Registry
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.CONTAINER_NAME }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.CONTAINER_NAME }}:latest

      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save ${{ secrets.CLUSTER_NAME }}

      - name: Update deployment image
        run: |
          kubectl set image statefulset/${DEPLOYMENT_NAME} ${CONTAINER_NAME}=${REGISTRY}/${CONTAINER_NAME}:${GITHUB_SHA}
          
      - name: Verify deployment
        run: |
          kubectl rollout status statefulset/${DEPLOYMENT_NAME}
